from typing import Any

def CalcROC(scores: Any, col: Any): ...
def CalcAUC(scores: Any, col: Any): ...
def CalcRIE(scores: Any, col: Any, alpha: Any): ...
def CalcBEDROC(scores: Any, col: Any, alpha: Any): ...
def CalcEnrichment(scores: Any, col: Any, fractions: Any): ...
