from typing import Any, Optional

class BitEnsemble:
    def __init__(self, bits: Optional[Any] = ...) -> None: ...
    def SetBits(self, bits: Any) -> None: ...
    def AddBit(self, bit: Any) -> None: ...
    def GetBits(self): ...
    def GetNumBits(self): ...
    def ScoreWithOnBits(self, other: Any): ...
    def ScoreWithIndex(self, other: Any): ...
