from typing import Any, Optional

class VisOpts:
    circRad: int = ...
    minCircRad: int = ...
    maxCircRad: int = ...
    circColor: Any = ...
    terminalEmptyColor: Any = ...
    terminalOnColor: Any = ...
    terminalOffColor: Any = ...
    outlineColor: Any = ...
    lineColor: Any = ...
    lineWidth: int = ...
    horizOffset: int = ...
    vertOffset: int = ...
    topMargin: int = ...
    labelFont: Any = ...
    highlightColor: Any = ...
    highlightWidth: int = ...

visOpts: Any

def GetMinCanvasSize(adjList: Any, levelList: Any): ...
def DrawHierarchy(adjList: Any, levelList: Any, canvas: Any, entryColors: Optional[Any] = ..., bitIds: Optional[Any] = ..., minLevel: int = ..., maxLevel: float = ...): ...
