from typing import Any, Optional

class TopNContainer:
    best: Any = ...
    extras: Any = ...
    def __init__(self, size: Any, mostNeg: Any = ...) -> None: ...
    def Insert(self, val: Any, extra: Optional[Any] = ...) -> None: ...
    def GetPts(self): ...
    def GetExtras(self): ...
    def __len__(self): ...
    def __getitem__(self, which: Any): ...
    def reverse(self) -> None: ...
