from rdkit import DataStructs as DataStructs
from typing import Any

class VectCollection:
    def __init__(self) -> None: ...
    def GetOrVect(self): ...
    orVect: Any = ...
    def AddVect(self, idx: Any, vect: Any) -> None: ...
    def Reset(self) -> None: ...
    def NumChildren(self): ...
    def GetChildren(self): ...
    def __getitem__(self, idx: Any): ...
    GetBit: Any = ...
    def __len__(self): ...
    GetNumBits: Any = ...
    def GetOnBits(self): ...
    def DetachVectsNotMatchingBit(self, bit: Any) -> None: ...
    def DetachVectsMatchingBit(self, bit: Any) -> None: ...
    def Uniquify(self, verbose: bool = ...) -> None: ...
