from .charge import ACID_BASE_PAIRS as ACID_BASE_PAIRS, CHARGE_CORRECTIONS as CHARGE_CORRECTIONS, Reionizer as Reionizer, Uncharger as Uncharger
from .fragment import FragmentRemover as FragmentRemover, LargestFragmentChooser as LargestFragmentChooser, PREFER_ORGANIC as PREFER_ORGANIC
from .metal import MetalDisconnector as MetalDisconnector
from .normalize import MAX_RESTARTS as MAX_RESTARTS, NORMALIZATIONS as NORMALIZATIONS, Normalizer as Normalizer
from .tautomer import MAX_TAUTOMERS as MAX_TAUTOMERS, TAUTOMER_SCORES as TAUTOMER_SCORES, TAUTOMER_TRANSFORMS as TAUTOMER_TRANSFORMS, TautomerCanonicalizer as TautomerCanonicalizer, TautomerEnumerator as TautomerEnumerator
from .utils import memoized_property as memoized_property
from rdkit import Chem as Chem
from typing import Any

log: Any

class Standardizer:
    normalizations: Any = ...
    acid_base_pairs: Any = ...
    charge_corrections: Any = ...
    tautomer_transforms: Any = ...
    tautomer_scores: Any = ...
    max_restarts: Any = ...
    max_tautomers: Any = ...
    prefer_organic: Any = ...
    def __init__(self, normalizations: Any = ..., acid_base_pairs: Any = ..., charge_corrections: Any = ..., tautomer_transforms: Any = ..., tautomer_scores: Any = ..., max_restarts: Any = ..., max_tautomers: Any = ..., prefer_organic: Any = ...) -> None: ...
    def __call__(self, mol: Any): ...
    def standardize(self, mol: Any): ...
    def tautomer_parent(self, mol: Any, skip_standardize: bool = ...): ...
    def fragment_parent(self, mol: Any, skip_standardize: bool = ...): ...
    def stereo_parent(self, mol: Any, skip_standardize: bool = ...): ...
    def isotope_parent(self, mol: Any, skip_standardize: bool = ...): ...
    def charge_parent(self, mol: Any, skip_standardize: bool = ...): ...
    def super_parent(self, mol: Any, skip_standardize: bool = ...): ...
    def standardize_with_parents(self, mol: Any): ...
    def disconnect_metals(self): ...
    def normalize(self): ...
    def reionize(self): ...
    def uncharge(self): ...
    def remove_fragments(self): ...
    def largest_fragment(self): ...
    def enumerate_tautomers(self): ...
    def canonicalize_tautomer(self): ...

def standardize_smiles(smiles: Any): ...
def enumerate_tautomers_smiles(smiles: Any): ...
def canonicalize_tautomer_smiles(smiles: Any): ...
