from rdkit import Chem as Chem
from typing import Any

def GetPrincipleQuantumNumber(atNum: Any): ...
def EStateIndices(mol: Any, force: bool = ...): ...
def MaxEStateIndex(mol: Any, force: int = ...): ...
def MinEStateIndex(mol: Any, force: int = ...): ...
def MaxAbsEStateIndex(mol: Any, force: int = ...): ...
def MinAbsEStateIndex(mol: Any, force: int = ...): ...
