- name: Emmanuel Noutahi
  email: emmanuel.noutahi@hotmail.ca
  aliases:
  - maclandrol
  num_commits: 0
  first_commit: 2020-10-25 10:15:22
  github: DomInvivo
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  aliases:
  - hadim
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 0
  first_commit: 2020-10-24 11:46:22
  github: matudor
- name: michelml
  email: michmoreau.l@gmail.com
  num_commits: 0
  first_commit: 2021-02-25 15:48:52
- name: Honoré Hounwanou
  email: mercuryseries@gmail.com
  num_commits: 0
  first_commit: 2021-02-12 17:01:32
- name: Therence1
  email: 38595485+Therence1@users.noreply.github.com
  num_commits: 0
  first_commit: 2021-04-03 17:31:09
- name: mike
  email: michael@invivoai.com
  num_commits: 0
  first_commit: 2021-03-30 16:03:51
- name: Ishan Kumar
  email: ishankumar216@gmail.com
  num_commits: 0
  first_commit: 2021-05-10 11:45:15
- name: deepsource-autofix[bot]
  email: 62050782+deepsource-autofix[bot]@users.noreply.github.com
  num_commits: 0
  first_commit: 2021-07-19 17:58:37
- name: DeepSource Bot
  email: bot@deepsource.io
  num_commits: 0
  first_commit: 2021-07-14 17:41:40
- name: Julien Horwood
  email: julien@invivoai.com
  num_commits: 0
  first_commit: 2022-01-26 17:14:26
- name: Cas
  email: caswognum@hotmail.com
  num_commits: 0
  first_commit: 2022-06-02 16:20:56
  aliases:
  - cwognum
  alternate_emails:
  - caswognum@outlook.com
  github: cwognum
- name: DomInvivo
  email: dominique@invivoai.com
  num_commits: 0
  first_commit: 2022-06-14 09:40:04
  github: DomInvivo
- name: Matt
  email: mtudor@proteovant.com
  num_commits: 0
  first_commit: 2022-08-09 16:54:28
  github: matudor
- name: Valence-JonnyHsu
  email: 104230580+Valence-JonnyHsu@users.noreply.github.com
  num_commits: 0
  first_commit: 2022-09-08 10:46:44
- name: Lu Zhu
  email: lu@valencediscovery.com
  num_commits: 0
  first_commit: 2022-09-07 13:45:44
- name: Saurav Maheshkar
  email: sauravvmaheshkar@gmail.com
  num_commits: 0
  first_commit: 2023-03-07 16:59:47
  github: SauravMaheshkar
- name: Pakman450
  email: steven.pak10@gmail.com
  num_commits: 0
  first_commit: 2023-03-30 00:37:39
  github: Pakman450
- name: dessygil
  email: desmondgilmour@gmail.com
  num_commits: 0
  first_commit: 2023-04-05 17:40:19
