[project]
name = "datamol"
version = "0.1.0"
description = "Add a short description here"
authors = ["Hadrien Mary <hadrien.mary@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "=3.11"
pip = "*"
tqdm = "*"
loguru = "*"
joblib = "*"
fsspec = ">=2021.9"
s3fs = ">=2021.9"
gcsfs = ">=2021.9"
platformdirs = "*"
packaging = "*"
typing_extensions = "*"
importlib_resources = "*"

# Scientific
pandas = "*"
numpy = "*"
scipy = "*"
pillow = "*"
matplotlib = "*"
scikit-learn = "*"

# Chemistry
rdkit = ">=2021.03"
selfies = "*"

# Optional deps
openpyxl = "*"
networkx = "*"
nglview = "*"
xlsxwriter = "*"
pyarrow = "*"

# Dev
pytest = ">=6.0"
pytest-cov = "*"
pytest-xdist = "*"
black = ">=23"
ruff = "*"
jupyterlab = "*"
mypy = "*"
codecov = "*"
nbconvert = "*"

# Doc
mkdocs = "*"
mkdocs-material = ">=7.1.1"
mkdocs-material-extensions = "*"
mkdocstrings = "*"
mkdocstrings-python = "*"
mkdocs-jupyter = "*"
markdown-include = "*"
mdx_truly_sane_lists = "*"
mike = ">=1.0.0"
seaborn = "*"
