from typing import Any

def log2(x: Any): ...
def BurgesRiskBound(VCDim: Any, nData: Any, nWrong: Any, conf: Any): ...
def CristianiRiskBound(VCDim: Any, nData: Any, nWrong: Any, conf: Any): ...
def CherkasskyRiskBound(VCDim: Any, nData: Any, nWrong: Any, conf: Any, a1: float = ..., a2: float = ...): ...
