from rdkit import Chem as Chem
from rdkit.Chem import rdMolDescriptors as rdMolDescriptors
from typing import Any, Optional

def ExplainAtomCode(code: Any, branchSubtract: int = ..., includeChirality: bool = ...): ...

GetAtomCode: Any

def NumPiElectrons(atom: Any): ...
def BitsInCommon(v1: Any, v2: Any): ...
def DiceSimilarity(v1: Any, v2: Any, bounds: Optional[Any] = ...): ...
def Dot(v1: Any, v2: Any): ...
def CosineSimilarity(v1: Any, v2: Any): ...
