from typing import Any
from win32com.client import constants as constants, gencache as gencache

cdxModule: Any
cdApp: Any
theDoc: Any
theObjs: Any
selectItem: Any
cleanItem: Any
centerItem: Any

def StartChemDraw(visible: bool = ..., openDoc: bool = ..., showDoc: bool = ...) -> None: ...
def ReactivateChemDraw(openDoc: bool = ..., showDoc: bool = ...) -> None: ...
def CDXConvert(inData: Any, inFormat: Any, outFormat: Any): ...
def CDXClean(inData: Any, inFormat: Any, outFormat: Any): ...
def CDXDisplay(inData: Any, inFormat: str = ..., clear: int = ...) -> None: ...
def CDXGrab(outFormat: str = ...): ...
def CloseChemdraw() -> None: ...
def Exit() -> None: ...
def SaveChemDrawDoc(fileName: str = ...) -> None: ...
def CloseChemDrawDoc() -> None: ...
def RaiseWindowNamed(nameRe: Any): ...
def RaiseChemDraw() -> None: ...
def SmilesToPilImage(smilesStr: Any): ...
def MolToPilImage(dataStr: Any, inFormat: str = ..., outFormat: str = ...): ...

c3dApp: Any

def StartChem3D(visible: int = ...) -> None: ...
def CloseChem3D() -> None: ...

availChem3DProps: Any

def Add3DCoordsToMol(data: Any, format: Any, props: Any = ...): ...
def OptimizeSDFile(inFileName: Any, outFileName: Any, problemFileName: str = ..., restartEvery: int = ...) -> None: ...
