from rdkit import Chem as Chem
from rdkit.Chem.Suppliers.MolSupplier import MolSupplier as MolSupplier
from typing import Any, Optional

def warning(msg: Any, dest: Any = ...) -> None: ...

class DbMolSupplier(MolSupplier):
    molCol: int = ...
    transformFunc: Any = ...
    nameCol: Any = ...
    molFmt: Any = ...
    def __init__(self, dbResults: Any, molColumnFormats: Any = ..., nameCol: str = ..., transformFunc: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def GetColumnNames(self): ...

class ForwardDbMolSupplier(DbMolSupplier):
    def __init__(self, dbResults: Any, **kwargs: Any) -> None: ...
    def Reset(self) -> None: ...
    def NextMol(self): ...

class RandomAccessDbMolSupplier(DbMolSupplier):
    def __init__(self, dbResults: Any, **kwargs: Any) -> None: ...
    def __len__(self): ...
    def __getitem__(self, idx: Any): ...
    def Reset(self) -> None: ...
    def NextMol(self): ...
