from rdkit import Chem as Chem
from rdkit.VLib.Supply import SupplyNode as SupplyNode
from typing import Any

class SDSupplyNode(SupplyNode):
    def __init__(self, fileName: Any, **kwargs: Any) -> None: ...
    def reset(self) -> None: ...
    def next(self): ...
