from rdkit import Chem as Chem
from rdkit.VLib.Filter import FilterNode as FilterNode
from typing import Any

class DupeFilter(FilterNode):
    def __init__(self, **kwargs: Any) -> None: ...
    def reset(self) -> None: ...
    def filter(self, cmpd: Any): ...
