from typing import Any

class SkeletonPoint:
    location: Any = ...
    shapeMoments: Any = ...
    shapeDirs: Any = ...
    molFeatures: Any = ...
    featmapFeatures: Any = ...
    fracVol: float = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class ShapeWithSkeleton:
    grid: Any = ...
    skelPts: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SubshapeShape:
    shapes: Any = ...
    featMap: Any = ...
    keyFeat: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def DisplaySubshapeSkeleton(viewer: Any, shape: Any, name: Any, color: Any = ..., colorByOrder: bool = ...) -> None: ...
def DisplaySubshape(viewer: Any, shape: Any, name: Any, showSkelPts: bool = ..., color: Any = ...) -> None: ...
