from typing import Any

StandardEnglishFonts: Any
widths: Any
ascent_descent: Any

def parseAFMfile(filename: Any): ...

class FontCache:
    def __init__(self) -> None: ...
    def loadfont(self, fontname: Any) -> None: ...
    def getfont(self, fontname: Any): ...
    def stringwidth(self, text: Any, font: Any): ...
    def status(self): ...

TheFontCache: Any
stringwidth: Any
