from rdkit import DataStructs as DataStructs
from rdkit.VLib.Node import VLibNode as VLibNode
from typing import Any

class DbFpSupplier(VLibNode):
    fpCol: Any = ...
    def __init__(self, dbResults: Any, fpColName: str = ..., usePickles: bool = ...) -> None: ...
    def GetColumnNames(self): ...
    def next(self): ...
    __next__: Any = ...

class ForwardDbFpSupplier(DbFpSupplier):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def reset(self) -> None: ...
    def NextItem(self): ...

class RandomAccessDbFpSupplier(DbFpSupplier):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self): ...
    def __getitem__(self, idx: Any): ...
    def reset(self) -> None: ...
    def NextItem(self): ...
