from rdkit import Chem as Chem, DataStructs as DataStructs
from rdkit.Chem.Fingerprints import DbFpSupplier as DbFpSupplier, FingerprintMols as FingerprintMols
from rdkit.DataStructs.TopNContainer import TopNContainer as TopNContainer
from rdkit.Dbase import DbModule as DbModule
from rdkit.Dbase.DbConnection import DbConnect as DbConnect
from typing import Any, Optional

def ScreenInDb(details: Any, mol: Any): ...
def GetFingerprints(details: Any): ...
def ScreenFingerprints(details: Any, data: Any, mol: Optional[Any] = ..., probeFp: Optional[Any] = ...): ...
def ScreenFromDetails(details: Any, mol: Optional[Any] = ...): ...
