from typing import Any

class DescriptorCalculator:
    simpleList: Any = ...
    descriptorNames: Any = ...
    compoundList: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def ShowDescriptors(self) -> None: ...
    def GetDescriptorNames(self) -> None: ...
    def SaveState(self, fileName: Any) -> None: ...
    def CalcDescriptors(self, what: Any, *args: Any, **kwargs: Any) -> None: ...
