from rdkit.ML.Descriptors import Descriptors as Descriptors
from rdkit.RDLogger import logger as logger
from typing import Any

class MolecularDescriptorCalculator(Descriptors.DescriptorCalculator):
    simpleList: Any = ...
    descriptorNames: Any = ...
    compoundList: Any = ...
    def __init__(self, simpleList: Any, *args: Any, **kwargs: Any) -> None: ...
    def SaveState(self, fileName: Any) -> None: ...
    def CalcDescriptors(self, mol: Any, *args: Any, **kwargs: Any): ...
    def GetDescriptorNames(self): ...
    def GetDescriptorSummaries(self): ...
    def GetDescriptorFuncs(self): ...
    def GetDescriptorVersions(self): ...
