from math import *
from rdkit import RDConfig as RDConfig
from typing import Any

knownMethods: Any

def HAS(strArg: Any, composList: Any, atomDict: Any): ...
def SUM(strArg: Any, composList: Any, atomDict: Any): ...
def MEAN(strArg: Any, composList: Any, atomDict: Any): ...
AVG = MEAN

def DEV(strArg: Any, composList: Any, atomDict: Any): ...
def MIN(strArg: Any, composList: Any, atomDict: Any): ...
def MAX(strArg: Any, composList: Any, atomDict: Any): ...
def CalcSingleCompoundDescriptor(compos: Any, argVect: Any, atomDict: Any, propDict: Any): ...
def CalcMultipleCompoundsDescriptor(composVect: Any, argVect: Any, atomDict: Any, propDictList: Any): ...
