from rdkit.VLib.Node import VLibNode as VLibNode
from typing import Any, Optional

class FilterNode(VLibNode):
    def __init__(self, func: Optional[Any] = ..., negate: int = ..., **kwargs: Any) -> None: ...
    def SetNegate(self, state: Any) -> None: ...
    def Negate(self): ...
    def next(self): ...
