from typing import Any

class VLibNode:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def next(self) -> None: ...
    def reset(self) -> None: ...
    def AddChild(self, child: Any, notify: int = ...) -> None: ...
    def RemoveChild(self, child: Any, notify: int = ...) -> None: ...
    def GetChildren(self): ...
    def AddParent(self, parent: Any, notify: bool = ...) -> None: ...
    def RemoveParent(self, parent: Any, notify: bool = ...) -> None: ...
    def GetParents(self): ...
    def Destroy(self, notify: bool = ..., propagateDown: bool = ..., propagateUp: bool = ...) -> None: ...
