from typing import Any

def GetNodeList(cluster: Any): ...
def GetNodesDownToCentroids(cluster: Any, above: int = ...): ...
def FindClusterCentroidFromDists(cluster: Any, dists: Any): ...
def SplitIntoNClusters(cluster: Any, n: Any, breadthFirst: bool = ...): ...
