from typing import Any, Optional

def EuclideanDistance(inData: Any): ...
def CalcMetricMatrix(inData: Any, metricFunc: Any): ...
def FindMinValInList(mat: Any, nObjs: Any, minIdx: Optional[Any] = ...): ...
def ShowMetricMat(metricMat: Any, nObjs: Any) -> None: ...

methods: Any
