from rdkit.DataStructs.TopNContainer import TopNContainer as TopNContainer
from typing import Any, Optional

class KNNModel:
    def __init__(self, k: Any, attrs: Any, dfunc: Any, radius: Optional[Any] = ...) -> None: ...
    def GetName(self): ...
    def SetName(self, name: Any) -> None: ...
    def GetExamples(self): ...
    def SetExamples(self, examples: Any) -> None: ...
    def GetTrainingExamples(self): ...
    def SetTrainingExamples(self, examples: Any) -> None: ...
    def GetTestExamples(self): ...
    def SetTestExamples(self, examples: Any) -> None: ...
    def GetNeighbors(self, example: Any): ...
