from rdkit import DataStructs as DataStructs
from typing import Any

class BitClusterer:
    def __init__(self, idList: Any, nCluster: Any, type: Any = ...) -> None: ...
    def ClusterBits(self, corrMat: Any) -> None: ...
    def SetClusters(self, clusters: Any) -> None: ...
    def GetClusters(self): ...
    def MapToClusterScores(self, fp: Any): ...
    def MapToClusterFP(self, fp: Any): ...
