from rdkit import Chem as Chem, RDLogger as RDLogger
from rdkit.Chem import ChemicalFeatures as ChemicalFeatures
from typing import Any

logger: Any
splitExpr: Any

def GetAtomFeatInfo(factory: Any, mol: Any): ...
def initParser(): ...
def existingFile(filename: Any): ...
def processArgs(args: Any, parser: Any) -> None: ...
def main() -> None: ...
