from rdkit.Chem.rdfiltercatalog import *
from rdkit import Chem as Chem
from typing import Any

class FilterMatcher(PythonFilterMatcher):
    name: Any = ...
    def __init__(self, name: str = ...) -> None: ...
    def HasMatch(self, mol: Any) -> None: ...
    def GetMatches(self, mol: Any, matchVect: Any): ...
    def IsValid(self, mol: Any) -> None: ...
    def GetName(self): ...
