from rdkit.Chem.rdfragcatalog import *
from rdkit import Chem as Chem
from typing import Any

def message(msg: Any, dest: Any = ...) -> None: ...

class BitGainsInfo:
    id: int = ...
    description: str = ...
    gain: float = ...
    nPerClass: Any = ...

def ProcessGainsFile(fileName: Any, nToDo: int = ..., delim: str = ..., haveDescriptions: int = ...): ...
def BuildAdjacencyList(catalog: Any, bits: Any, limitInclusion: int = ..., orderLevels: int = ...): ...
def GetMolsMatchingBit(mols: Any, bit: Any, fps: Any): ...
