from rdkit import Chem as Chem
from typing import Any

class FragmentMatcher:
    def __init__(self) -> None: ...
    def AddExclusion(self, sma: Any) -> None: ...
    def Init(self, sma: Any) -> None: ...
    def GetSMARTS(self) -> None: ...
    def GetExclusionSMARTS(self) -> None: ...
    def HasMatch(self, mol: Any): ...
    def GetMatch(self, mol: Any): ...
    def GetMatches(self, mol: Any, uniquify: int = ...): ...
    def GetBond(self, idx: Any): ...
