from rdkit import Chem as Chem, RDConfig as RDConfig
from typing import Any, Optional

class FGHierarchyNode:
    children: Any = ...
    name: str = ...
    label: str = ...
    pattern: Any = ...
    smarts: str = ...
    rxnSmarts: str = ...
    parent: Any = ...
    removalReaction: Any = ...
    def __init__(self, name: Any, patt: Any, smarts: str = ..., label: str = ..., rxnSmarts: str = ..., parent: Optional[Any] = ...) -> None: ...
    def __len__(self): ...

class FuncGroupFileParseError(ValueError): ...

groupDefns: Any
hierarchy: Any
lastData: Any
lastFilename: Any

def BuildFuncGroupHierarchy(fileNm: Optional[Any] = ..., data: Optional[Any] = ..., force: bool = ...): ...
def CreateMolFingerprint(mol: Any, hierarchy: Any): ...
