from typing import Any, Optional

class MCSResult:
    numAtoms: Any = ...
    numBonds: Any = ...
    smarts: Any = ...
    completed: Any = ...
    def __init__(self, obj: Any) -> None: ...
    def __nonzero__(self): ...

def FindMCS(mols: Any, minNumAtoms: int = ..., maximize: Any = ..., atomCompare: Any = ..., bondCompare: Any = ..., matchValences: Any = ..., ringMatchesRingOnly: bool = ..., completeRingsOnly: bool = ..., timeout: Any = ..., threshold: Optional[Any] = ...): ...
