from rdkit import Chem as Chem
from typing import Any

class PropertyMol(Chem.Mol):
    __getstate_manages_dict__: bool = ...
    def __init__(self, mol: Any) -> None: ...
    def SetProp(self, nm: Any, val: Any) -> None: ...
