import Boost.Python

def RunMol(RDKit) -> Any: ...

class EHTResults(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def GetAtomicCharges(RDKit) -> Any: ...
    @classmethod
    def GetHamiltonian(RDKit) -> Any: ...
    @classmethod
    def GetOrbitalEnergies(RDKit) -> Any: ...
    @classmethod
    def GetOverlapMatrix(RDKit) -> Any: ...
    @classmethod
    def GetReducedChargeMatrix(RDKit) -> Any: ...
    @classmethod
    def GetReducedOverlapPopulationMatrix(RDKit) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def fermiEnergy(self) -> Any: ...
    @property
    def numElectrons(self) -> Any: ...
    @property
    def numOrbitals(self) -> Any: ...
    @property
    def totalEnergy(self) -> Any: ...
