import Boost.Python

class FragCatGenerator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def AddFragsFromMol(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class FragCatParams(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def GetFuncGroup(RDKit, int) -> Any: ...
    @classmethod
    def GetLowerFragLength(RDKit) -> Any: ...
    @classmethod
    def GetNumFuncGroups(RDKit) -> Any: ...
    @classmethod
    def GetTolerance(RDKit) -> Any: ...
    @classmethod
    def GetTypeString(RDKit) -> Any: ...
    @classmethod
    def GetUpperFragLength(RDKit) -> Any: ...
    @classmethod
    def Serialize(RDKit) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class FragCatalog(Boost.Python.instance):
    __instance_size__: Any = ...
    __safe_for_unpickling__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def GetBitDescription(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBitDiscrims(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBitEntryId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBitFuncGroupIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBitOrder(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetCatalogParams(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryBitId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryDescription(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryDownIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryFuncGroupIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryOrder(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetFPLength(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumEntries(self, *args, **kwargs) -> Any: ...
    @classmethod
    def Serialize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __getinitargs__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class FragFPGenerator(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def GetFPForMol(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
