import Boost.Python

class MHFPEncoder(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def CreateShinglingFromMol(self, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateShinglingFromSmiles(self, *args, **kwargs) -> Any: ...
    def Distance(self, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeMol(self, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeMolsBulk(RDKit, boost) -> Any: ...
    @classmethod
    def EncodeSECFPMol(self, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeSECFPMolsBulk(RDKit, boost) -> Any: ...
    @classmethod
    def EncodeSECFPSmiles(self, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeSECFPSmilesBulk(RDKit, boost) -> Any: ...
    @classmethod
    def EncodeSmiles(self, *args, **kwargs) -> Any: ...
    @classmethod
    def EncodeSmilesBulk(RDKit, boost) -> Any: ...
    @classmethod
    def FromArray(RDKit, boost) -> Any: ...
    @classmethod
    def FromStringArray(RDKit, boost) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
