import Boost.Python

def Enumerate(*args, **kwargs) -> Any: ...

class EnumeratorType(Boost.Python.enum):
    LinkNode: Any = ...
    PositionVariation: Any = ...
    names: Any = ...
    values: Any = ...
    __slots__: Any = ...

class MolEnumeratorParams(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(boost, (anonymousnamespace)) -> Any: ...
    @classmethod
    def SetEnumerationOperator(RDKit, (anonymousnamespace)) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def doRandom(self) -> Any: ...
    @doRandom.setter
    def doRandom(self, val: Any) -> None: ...
    @property
    def maxToEnumerate(self) -> Any: ...
    @maxToEnumerate.setter
    def maxToEnumerate(self, val: Any) -> None: ...
    @property
    def randomSeed(self) -> Any: ...
    @randomSeed.setter
    def randomSeed(self, val: Any) -> None: ...
    @property
    def sanitize(self) -> Any: ...
    @sanitize.setter
    def sanitize(self, val: Any) -> None: ...
