import Boost.Python

def AlignMol(*args, **kwargs) -> Any: ...
def AlignMolConformers(*args, **kwargs) -> Any: ...
def CalcRMS(*args, **kwargs) -> Any: ...
def GetAlignmentTransform(*args, **kwargs) -> Any: ...
def GetBestRMS(*args, **kwargs) -> Any: ...
def GetCrippenO3A(*args, **kwargs) -> Any: ...
def GetCrippenO3AForProbeConfs(*args, **kwargs) -> Any: ...
def GetO3A(*args, **kwargs) -> Any: ...
def GetO3AForProbeConfs(*args, **kwargs) -> Any: ...
def RandomTransform(RDKit) -> Any: ...

class O3A(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def Align(RDKit) -> Any: ...
    @classmethod
    def Matches(RDKit) -> Any: ...
    @classmethod
    def Score(RDKit) -> Any: ...
    @classmethod
    def Trans(RDKit) -> Any: ...
    @classmethod
    def Weights(RDKit) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
