import Boost.Python

def JSONToMols(*args, **kwargs) -> Any: ...
def MolToJSON(RDKit) -> Any: ...
def MolsToJSON(boost) -> Any: ...

class JSONParseParameters(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @property
    def parseConformers(self) -> Any: ...
    @parseConformers.setter
    def parseConformers(self, val: Any) -> None: ...
    @property
    def parseProperties(self) -> Any: ...
    @parseProperties.setter
    def parseProperties(self, val: Any) -> None: ...
    @property
    def setAromaticBonds(self) -> Any: ...
    @setAromaticBonds.setter
    def setAromaticBonds(self, val: Any) -> None: ...
    @property
    def strictValenceCheck(self) -> Any: ...
    @strictValenceCheck.setter
    def strictValenceCheck(self, val: Any) -> None: ...
