import Boost.Python

def CreateMolCatalog(*args, **kwargs) -> Any: ...

class MolCatalog(Boost.Python.instance):
    __instance_size__: Any = ...
    __safe_for_unpickling__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def AddEdge(self, *args, **kwargs) -> Any: ...
    @classmethod
    def AddEntry(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBitDescription(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetBitEntryId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryBitId(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryDescription(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEntryDownIds(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetFPLength(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumEntries(self, *args, **kwargs) -> Any: ...
    @classmethod
    def Serialize(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __getinitargs__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class MolCatalogEntry(Boost.Python.instance):
    __instance_size__: Any = ...
    __safe_for_unpickling__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def GetDescription(RDKit) -> Any: ...
    @classmethod
    def GetMol(RDKit) -> Any: ...
    @classmethod
    def GetOrder(RDKit) -> Any: ...
    @classmethod
    def SetDescription(self, *args, **kwargs) -> Any: ...
    @classmethod
    def SetMol(self, *args, **kwargs) -> Any: ...
    @classmethod
    def SetOrder(RDKit, unsignedint) -> Any: ...
    @classmethod
    def __getinitargs__(RDKit) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
