import Boost.Python

def MolHash(*args, **kwargs) -> Any: ...

class HashFunction(Boost.Python.enum):
    AnonymousGraph: Any = ...
    ArthorSubstructureOrder: Any = ...
    AtomBondCounts: Any = ...
    CanonicalSmiles: Any = ...
    DegreeVector: Any = ...
    ElementGraph: Any = ...
    ExtendedMurcko: Any = ...
    HetAtomProtomer: Any = ...
    HetAtomTautomer: Any = ...
    Mesomer: Any = ...
    MolFormula: Any = ...
    MurckoScaffold: Any = ...
    NetCharge: Any = ...
    RedoxPair: Any = ...
    Regioisomer: Any = ...
    SmallWorldIndexBR: Any = ...
    SmallWorldIndexBRL: Any = ...
    names: Any = ...
    values: Any = ...
    __slots__: Any = ...
