import Boost.Python

def BuildFeatureFactory(*args, **kwargs) -> Any: ...
def BuildFeatureFactoryFromString(*args, **kwargs) -> Any: ...
def GetAtomMatch(boost) -> Any: ...

class MolChemicalFeature(Boost.Python.instance):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def ClearCache(RDKit) -> Any: ...
    @classmethod
    def GetActiveConformer(RDKit) -> Any: ...
    @classmethod
    def GetAtomIds(RDKit) -> Any: ...
    @classmethod
    def GetFactory(RDKit) -> Any: ...
    @classmethod
    def GetFamily(RDKit) -> Any: ...
    @classmethod
    def GetId(RDKit) -> Any: ...
    @classmethod
    def GetMol(RDKit) -> Any: ...
    @classmethod
    def GetPos(RDKit) -> Any: ...
    @classmethod
    def GetType(RDKit) -> Any: ...
    @classmethod
    def SetActiveConformer(RDKit, int) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class MolChemicalFeatureFactory(Boost.Python.instance):
    GetFeaturesForMol: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def GetFeatureDefs(RDKit) -> Any: ...
    @classmethod
    def GetFeatureFamilies(RDKit) -> Any: ...
    @classmethod
    def GetMolFeature(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetNumFeatureDefs(RDKit) -> Any: ...
    @classmethod
    def GetNumMolFeatures(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
