import Boost.Python

def PatternFingerprintTautomerTarget(RDKit) -> Any: ...

class TautomerQuery(Boost.Python.instance):
    @classmethod
    def __init__(boost, RDKit) -> Any: ...
    @classmethod
    def GetModifiedAtoms(RDKit) -> Any: ...
    @classmethod
    def GetModifiedBonds(RDKit) -> Any: ...
    @classmethod
    def GetSubstructMatch(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSubstructMatches(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSubstructMatchesWithTautomers(self, *args, **kwargs) -> Any: ...
    @classmethod
    def GetTautomers(RDKit) -> Any: ...
    @classmethod
    def GetTemplateMolecule(RDKit) -> Any: ...
    @classmethod
    def IsSubstructOf(self, *args, **kwargs) -> Any: ...
    @classmethod
    def PatternFingerprintTemplate(RDKit) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...

class UnsignedLong_Vect(Boost.Python.instance):
    __instance_size__: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def append(self, *args, **kwargs) -> Any: ...
    @classmethod
    def extend(self, *args, **kwargs) -> Any: ...
    @classmethod
    def __contains__(self, other) -> Any: ...
    @classmethod
    def __delitem__(self, other) -> Any: ...
    @classmethod
    def __getitem__(self, index) -> Any: ...
    @classmethod
    def __iter__(boost, std) -> Any: ...
    @classmethod
    def __len__(self) -> Any: ...
    @classmethod
    def __reduce__(self) -> Any: ...
    @classmethod
    def __setitem__(self, index, object) -> Any: ...
