from typing import overload

def ReadAmberTrajectory(*args, **kwargs) -> Any: ...
def ReadGromosTrajectory(*args, **kwargs) -> Any: ...
@overload
def Snapshot(boost) -> Any: ...
@overload
def Snapshot(RDKit) -> Any: ...
def Trajectory(RDKit) -> Any: ...
