from rdkit import Chem as Chem
from typing import Any, Optional

reactionDefs: Any
reactions: Any

class RecapHierarchyNode:
    mol: Any = ...
    children: Any = ...
    parents: Any = ...
    smiles: Any = ...
    def __init__(self, mol: Any) -> None: ...
    def GetAllChildren(self): ...
    def GetLeaves(self): ...
    def getUltimateParents(self): ...
    def __del__(self) -> None: ...

def RecapDecompose(mol: Any, allNodes: Optional[Any] = ..., minFragmentSize: int = ..., onlyUseReactions: Optional[Any] = ...): ...
