from rdkit import Chem as Chem, RDConfig as RDConfig
from rdkit.Chem.rdmolfiles import SDMolSupplier as SDMolSupplier, SmilesMolSupplier as SmilesMolSupplier
from typing import Any, Optional

class InputFormat:
    SMARTS: str = ...
    MOL: str = ...
    SMILES: str = ...

class SaltRemover:
    defnFilename: Any = ...
    defnData: Any = ...
    salts: Any = ...
    defnFormat: Any = ...
    def __init__(self, defnFilename: Optional[Any] = ..., defnData: Optional[Any] = ..., defnFormat: Any = ...) -> None: ...
    def StripMol(self, mol: Any, dontRemoveEverything: bool = ...): ...
    def StripMolWithDeleted(self, mol: Any, dontRemoveEverything: bool = ...): ...
    def __call__(self, mol: Any, dontRemoveEverything: bool = ...): ...
