from rdkit import Chem as Chem, Geometry as Geometry
from rdkit.Chem import rdDepictor as rdDepictor
from typing import Any, Optional

def AlignDepict(mol: Any, core: Any, corePattern: Optional[Any] = ..., acceptFailure: bool = ...) -> None: ...
def initParser(): ...
def processArgs(args: Any) -> None: ...
def main() -> None: ...
