from rdkit import Chem as Chem, DataStructs as DataStructs
from typing import Any, Optional

similarityMethods: Any
supportedSimilarityMethods: Any

class LayeredOptions:
    loadLayerFlags: int = ...
    searchLayerFlags: int = ...
    minPath: int = ...
    maxPath: int = ...
    fpSize: int = ...
    wordSize: int = ...
    nWords: Any = ...
    @staticmethod
    def GetFingerprint(mol: Any, query: bool = ...): ...
    @staticmethod
    def GetWords(mol: Any, query: bool = ...): ...
    @staticmethod
    def GetQueryText(mol: Any, query: bool = ...): ...

def BuildSigFactory(options: Optional[Any] = ..., fdefFile: Optional[Any] = ..., bins: Any = ..., skipFeats: Any = ...): ...
def BuildAtomPairFP(mol: Any): ...
def BuildTorsionsFP(mol: Any): ...
def BuildRDKitFP(mol: Any): ...
def BuildPharm2DFP(mol: Any): ...
def BuildMorganFP(mol: Any): ...
def BuildAvalonFP(mol: Any, smiles: Optional[Any] = ...): ...
def DepickleFP(pkl: Any, similarityMethod: Any): ...
