from typing import Any

class ExcludedVolume:
    index: Any = ...
    featInfo: Any = ...
    exclusionDist: Any = ...
    pos: Any = ...
    def __init__(self, featInfo: Any, index: int = ..., exclusionDist: float = ...) -> None: ...
