from rdkit import DataStructs as DataStructs
from rdkit.DataStructs.TopNContainer import TopNContainer as TopNContainer
from typing import Any, Optional

class GenericPicker:
    def MakePicks(self, force: bool = ...) -> None: ...
    def __len__(self): ...
    def __getitem__(self, which: Any): ...

class TopNOverallPicker(GenericPicker):
    numToPick: Any = ...
    probes: Any = ...
    data: Any = ...
    simMetric: Any = ...
    def __init__(self, numToPick: int = ..., probeFps: Optional[Any] = ..., dataSet: Optional[Any] = ..., simMetric: Any = ...) -> None: ...
    def MakePicks(self, force: bool = ...) -> None: ...

class SpreadPicker(GenericPicker):
    numToPick: Any = ...
    probes: Any = ...
    data: Any = ...
    simMetric: Any = ...
    expectPickles: Any = ...
    onlyNames: Any = ...
    def __init__(self, numToPick: int = ..., probeFps: Optional[Any] = ..., dataSet: Optional[Any] = ..., simMetric: Any = ..., expectPickles: bool = ..., onlyNames: bool = ...) -> None: ...
    def MakePicks(self, force: bool = ..., silent: bool = ...) -> None: ...
