from rdkit.Chem.FeatMaps import FeatMaps as FeatMaps
from typing import Any

class MergeMethod:
    WeightedAverage: int = ...
    Average: int = ...
    UseLarger: int = ...
    @classmethod
    def valid(cls, mergeMethod: Any) -> None: ...

class MergeMetric:
    NoMerge: int = ...
    Distance: int = ...
    Overlap: int = ...
    @classmethod
    def valid(cls, mergeMetric: Any) -> None: ...

class DirMergeMode:
    NoMerge: int = ...
    Sum: int = ...
    @classmethod
    def valid(cls, dirMergeMode: Any) -> None: ...

def GetFeatFeatDistMatrix(fm: Any, mergeMetric: Any, mergeTol: Any, dirMergeMode: Any, compatFunc: Any): ...
def familiesMatch(f1: Any, f2: Any): ...
def feq(v1: Any, v2: Any, tol: float = ...): ...
def MergeFeatPoints(fm: Any, mergeMetric: Any = ..., mergeTol: float = ..., dirMergeMode: Any = ..., mergeMethod: Any = ..., compatFunc: Any = ...): ...
def CombineFeatMaps(fm1: Any, fm2: Any, mergeMetric: Any = ..., mergeTol: float = ..., dirMergeMode: Any = ...): ...
