import Boost.Python
avalonSSSBits: int
avalonSimilarityBits: int

def CheckMolecule(RDKit) -> Any: ...
def CheckMoleculeString(*args, **kwargs) -> Any: ...
def CloseCheckMolFiles(*args, **kwargs) -> Any: ...
def Generate2DCoords(RDKit) -> Any: ...
def GetAvalonCountFP(RDKit) -> Any: ...
def GetAvalonFP(RDKit) -> Any: ...
def GetAvalonFPAsWords(RDKit) -> Any: ...
def GetCanonSmiles(RDKit) -> Any: ...
def GetCheckMolLog(*args, **kwargs) -> Any: ...
def InitializeCheckMol(*args, **kwargs) -> Any: ...

class StruChkFlag(Boost.Python.enum):
    alias_conversion_failed: Any = ...
    atom_check_failed: Any = ...
    atom_clash: Any = ...
    bad_molecule: Any = ...
    dubious_stereo_removed: Any = ...
    either_warning: Any = ...
    fragments_found: Any = ...
    names: Any = ...
    recharged: Any = ...
    size_check_failed: Any = ...
    stereo_error: Any = ...
    stereo_forced_bad: Any = ...
    stereo_transformed: Any = ...
    template_transformed: Any = ...
    transformed: Any = ...
    values: Any = ...
    __slots__: Any = ...

class StruChkResult(Boost.Python.enum):
    bad_set: Any = ...
    names: Any = ...
    success: Any = ...
    transformed_set: Any = ...
    values: Any = ...
    __slots__: Any = ...
