from rdkit.ML.DecTree import Tree as Tree
from typing import Any, Optional

class DecTreeNode(Tree.TreeNode):
    examples: Any = ...
    badExamples: Any = ...
    trainingExamples: Any = ...
    testExamples: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def ClassifyExample(self, example: Any, appendExamples: int = ...): ...
    def AddChild(self, name: Any, label: Optional[Any] = ..., data: Optional[Any] = ..., isTerminal: int = ...): ...
    def GetExamples(self): ...
    def SetExamples(self, examples: Any) -> None: ...
    def GetBadExamples(self): ...
    def SetBadExamples(self, examples: Any) -> None: ...
    def GetTrainingExamples(self): ...
    def SetTrainingExamples(self, examples: Any) -> None: ...
    def GetTestExamples(self): ...
    def SetTestExamples(self, examples: Any) -> None: ...
    def ClearExamples(self) -> None: ...
