from rdkit.ML.DecTree import CrossValidate as CrossValidate, DecTree as DecTree
from typing import Any

def MaxCount(examples: Any): ...
def PruneTree(tree: Any, trainExamples: Any, testExamples: Any, minimizeTestErrorOnly: int = ...): ...
