from rdkit.ML.DecTree import DecTree as DecTree, Tree as Tree
from typing import Any

class QuantTreeNode(DecTree.DecTreeNode):
    qBounds: Any = ...
    nBounds: int = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def ClassifyExample(self, example: Any, appendExamples: int = ...): ...
    def SetQuantBounds(self, qBounds: Any) -> None: ...
    def GetQuantBounds(self): ...
    def __cmp__(self, other: Any): ...
    def __lt__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
