from rdkit.DataStructs.VectCollection import VectCollection as VectCollection
from rdkit.ML.DecTree import DecTree as DecTree
from typing import Any

class SigTreeNode(DecTree.DecTreeNode):
    def NameModel(self, *args: Any, **kwargs: Any) -> None: ...
    def ClassifyExample(self, example: Any, appendExamples: int = ...): ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
