from typing import Any

class VisOpts:
    circRad: int = ...
    minCircRad: int = ...
    maxCircRad: int = ...
    circColor: Any = ...
    terminalEmptyColor: Any = ...
    terminalOnColor: Any = ...
    terminalOffColor: Any = ...
    outlineColor: Any = ...
    lineColor: Any = ...
    lineWidth: int = ...
    horizOffset: int = ...
    vertOffset: int = ...
    labelFont: Any = ...
    highlightColor: Any = ...
    highlightWidth: int = ...

visOpts: Any

def CalcTreeNodeSizes(node: Any) -> None: ...
def SetNodeScales(node: Any) -> None: ...
def DrawTreeNode(node: Any, loc: Any, canvas: Any, nRes: int = ..., scaleLeaves: bool = ..., showPurity: bool = ...) -> None: ...
def CalcTreeWidth(tree: Any): ...
def DrawTree(tree: Any, canvas: Any, nRes: int = ..., scaleLeaves: bool = ..., allowShrink: bool = ..., showPurity: bool = ...) -> None: ...
def ResetTree(tree: Any) -> None: ...
