from typing import Any

def CollectLabelLevels(tree: Any, levels: Any, level: int = ..., maxDepth: float = ...): ...
def CollectDescriptorNames(tree: Any, names: Any, level: int = ..., maxDepth: float = ...): ...
