from rdkit.ML.Composite import Composite as Composite
from typing import Any

class BayesComposite(Composite.Composite):
    resultProbs: Any = ...
    condProbs: Any = ...
    def Train(self, data: Any, verbose: int = ...) -> None: ...
    modelVotes: Any = ...
    def ClassifyExample(self, example: Any, threshold: int = ..., verbose: int = ..., appendExample: int = ...): ...
    def __init__(self) -> None: ...

def CompositeToBayesComposite(obj: Any) -> None: ...
def BayesCompositeToComposite(obj: Any) -> None: ...
