from rdkit.Dbase import DbInfo as DbInfo, DbModule as DbModule, DbUtils as DbUtils
from typing import Any, Optional

class DbError(RuntimeError): ...

class DbConnect:
    dbName: Any = ...
    tableName: Any = ...
    user: Any = ...
    password: Any = ...
    cn: Any = ...
    cursor: Any = ...
    def __init__(self, dbName: str = ..., tableName: str = ..., user: str = ..., password: str = ...) -> None: ...
    def GetTableNames(self, includeViews: int = ...): ...
    def GetColumnNames(self, table: str = ..., join: str = ..., what: str = ..., where: str = ..., **kwargs: Any): ...
    def GetColumnNamesAndTypes(self, table: str = ..., join: str = ..., what: str = ..., where: str = ..., **kwargs: Any): ...
    def GetColumns(self, fields: Any, table: str = ..., join: str = ..., **kwargs: Any): ...
    def GetData(self, table: Optional[Any] = ..., fields: str = ..., where: str = ..., removeDups: int = ..., join: str = ..., transform: Optional[Any] = ..., randomAccess: int = ..., **kwargs: Any): ...
    def GetDataCount(self, table: Optional[Any] = ..., where: str = ..., join: str = ..., **kwargs: Any): ...
    def GetCursor(self): ...
    def KillCursor(self) -> None: ...
    def AddTable(self, tableName: Any, colString: Any) -> None: ...
    def InsertData(self, tableName: Any, vals: Any) -> None: ...
    def InsertColumnData(self, tableName: Any, columnName: Any, value: Any, where: Any) -> None: ...
    def AddColumn(self, tableName: Any, colName: Any, colType: Any) -> None: ...
    def Commit(self) -> None: ...
