from rdkit.Dbase import DbInfo as DbInfo
from typing import Any, Optional

class DbResultBase:
    cursor: Any = ...
    removeDups: Any = ...
    transform: Any = ...
    cmd: Any = ...
    conn: Any = ...
    extras: Any = ...
    def __init__(self, cursor: Any, conn: Any, cmd: Any, removeDups: int = ..., transform: Optional[Any] = ..., extras: Optional[Any] = ...) -> None: ...
    def Reset(self) -> None: ...
    def __iter__(self) -> Any: ...
    def GetColumnNames(self): ...
    def GetColumnTypes(self): ...
    def GetColumnNamesAndTypes(self): ...

class DbResultSet(DbResultBase):
    seen: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def Reset(self) -> None: ...
    def next(self): ...
    __next__: Any = ...

class RandomAccessDbResultSet(DbResultBase):
    results: Any = ...
    seen: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def Reset(self) -> None: ...
    cursor: Any = ...
    def __getitem__(self, idx: Any): ...
    def __len__(self): ...
    def next(self): ...
    __next__: Any = ...
