from rdkit import Chem as Chem, Geometry as Geometry
from typing import Any

def cross(v1: Any, v2: Any): ...
def findNeighbors(atomId: Any, adjMat: Any): ...
def GetAromaticFeatVects(conf: Any, featAtoms: Any, featLoc: Any, scale: float = ...): ...
def ArbAxisRotation(theta: Any, ax: Any, pt: Any): ...
def GetAcceptor2FeatVects(conf: Any, featAtoms: Any, scale: float = ...): ...
def GetDonor3FeatVects(conf: Any, featAtoms: Any, scale: float = ...): ...
def GetAcceptor3FeatVects(conf: Any, featAtoms: Any, scale: float = ...): ...
def GetDonor2FeatVects(conf: Any, featAtoms: Any, scale: float = ...): ...
def GetDonor1FeatVects(conf: Any, featAtoms: Any, scale: float = ...): ...
def GetAcceptor1FeatVects(conf: Any, featAtoms: Any, scale: float = ...): ...
