channels:
  - conda-forge

dependencies:
  - python >=3.8
  - pip
  - tqdm
  - loguru
  - joblib
  - fsspec >=2021.9
  - s3fs >=2021.9
  - gcsfs >=2021.9
  - platformdirs
  - packaging
  - typing_extensions
  - importlib_resources

  # Scientific
  - pandas
  - numpy
  - scipy
  - pillow
  - matplotlib
  - scikit-learn

  # Chemistry
  - rdkit >=2021.03
  - selfies

  # Optional deps
  - openpyxl
  - networkx
  - nglview
  - xlsxwriter
  - pyarrow

  # Dev
  - pytest >=6.0
  - pytest-cov
  - pytest-xdist
  - black >=23
  - jupyterlab
  - mypy
  - codecov
  - nbconvert

  # Doc
  - mkdocs
  - mkdocs-material >=7.1.1
  - mkdocs-material-extensions
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-jupyter
  - markdown-include
  - mdx_truly_sane_lists
  - mike >=1.0.0
  - seaborn
