from typing import Any

class ActFunc:
    def __call__(self, x: Any): ...

class Sigmoid(ActFunc):
    def Eval(self, x: Any): ...
    def Deriv(self, x: Any): ...
    def DerivFromVal(self, val: Any): ...
    beta: Any = ...
    def __init__(self, beta: float = ...) -> None: ...

class TanH(ActFunc):
    def Eval(self, x: Any): ...
    def Deriv(self, x: Any): ...
    def DerivFromVal(self, val: Any): ...
    beta: Any = ...
    def __init__(self, beta: float = ...) -> None: ...
