from typing import Any, Optional

class Trainer: ...

class BackProp(Trainer):
    oldDeltaW: Any = ...
    def StepUpdate(self, example: Any, net: Any, resVect: Optional[Any] = ...): ...
    def TrainOnLine(self, examples: Any, net: Any, maxIts: int = ..., errTol: float = ..., useAvgErr: int = ..., silent: int = ...) -> None: ...
    speed: Any = ...
    momentum: Any = ...
    def __init__(self, speed: float = ..., momentum: float = ...) -> None: ...
