name: test-with-pixi

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # NOTE(hadim): for now we cannot test a matrix since it does not seem
        # to be supported by pixi yet.
        # python-version: ["3.10", "3.11"]
        # os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # rdkit-version: ["2023.03", "2023.09"]
        python-version: ["3.11"]
        os: ["ubuntu-latest"]
        rdkit-version: ["2023.09"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: pixi run bash {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}
      - rdkit=${{ matrix.rdkit-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: v0.9.1
          cache: true
          locked: true
          frozen: false
          log-level: default # one of `q`, `default`, `v`, `vv`, or `vvv`.

      - name: Install library
        run: python -m pip install --no-deps -e . # `-e` required for correct `coverage` run.

      - name: Run tests
        run: pytest

      - name: Codecov Upload
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false
          env_vars: ${{ matrix.os }},${{ matrix.python-version }},${{ matrix.rdkit-version }}

      - name: Test building the doc
        run: mkdocs build
