from rdkit import DataStructs as DataStructs
from rdkit.Dbase import DbModule as DbModule
from rdkit.ML import CompositeRun as CompositeRun, ScreenComposite as ScreenComposite
from rdkit.ML.Composite import BayesComposite as BayesComposite, Composite as Composite
from rdkit.ML.Data import DataUtils as DataUtils, SplitData as SplitData
from rdkit.utils import listutils as listutils
from typing import Any, Optional

def message(msg: Any) -> None: ...
def testall(composite: Any, examples: Any, badExamples: Any = ...): ...
def GetCommandLine(details: Any): ...
def RunOnData(details: Any, data: Any, progressCallback: Optional[Any] = ..., saveIt: int = ..., setDescNames: int = ...): ...
def RunIt(details: Any, progressCallback: Optional[Any] = ..., saveIt: int = ..., setDescNames: int = ...): ...
def ShowVersion(includeArgs: int = ...) -> None: ...
def Usage() -> None: ...
def SetDefaults(runDetails: Optional[Any] = ...): ...
def ParseArgs(runDetails: Any) -> None: ...
