from typing import Any

class ReFile:
    def readline(self): ...
    def readlines(self): ...
    def rewind(self) -> None: ...
    regExp: Any = ...
    inFile: Any = ...
    def __init__(self, fileName: Any, mode: str = ..., comment: str = ..., trailer: str = ...) -> None: ...

def ReadDataFile(fileName: Any, comment: str = ..., depVarCol: int = ..., dataType: Any = ...): ...
